---
title: "Project 2 Dani"
author: "Danielle De La Paz"
date: "2020-05-01" 
output:
  html_document: default
  word_document: default
  pdf_document: default
---



<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<p>Introduction: The dataset I have chosen is called ‘hurricNamed’, this is the Named US Atlantic Hurricanes and their statistics. It consists of 94 observations with 11 variables. This first variable (name) is the Hurricane Name, the second (year) is the year it occurred in. The third is the maximum windspeed along the US coast labeled as LF.WindsMPH. The fourth is the LF.PressureMB which is the atmospheric pressure. The LF.times is the date of the first landfall, the BaseDam2014 is the property damage in millions if the hurricane would have been in 2014. The BaseDamage is the property damage in millions while NDAM2014 is the damage if the hurricane had happened in 2014. The AffectedStates is where the hurricane had occurred. The firstLF is the date of the first landfall. The deaths is the number of deaths during the hurricanes and the mf is the gender name of the hurricane which is also the binary variable in this project.
1.)</p>
<pre class="r"><code>library(readr)
hurricNamed_2 &lt;- read_csv(&quot;hurricNamed 2.csv&quot;)
hurricNamed&lt;-hurricNamed_2
library(dplyr)
dataomit&lt;-hurricNamed %&gt;% select(-Name)%&gt;% select(-BaseDamage) %&gt;% 
  select(-BaseDam2014) %&gt;% select(-mf) %&gt;% select(-LF.times)%&gt;% 
  select(-NDAM2014) %&gt;% 
  select(-AffectedStates)%&gt;%
  select(-firstLF) %&gt;%
  select(-deaths)
man1&lt;- manova(cbind(LF.WindsMPH, LF.PressureMB)~Year, data=dataomit)
summary(man1)</code></pre>
<pre><code>##           Df  Pillai approx F num Df den Df   Pr(&gt;F)    
## Year       1 0.28229   17.896      2     91 2.79e-07 ***
## Residuals 92                                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response LF.WindsMPH :
##             Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Year         1   2497 2497.39  5.1639 0.02539 *
## Residuals   92  44493  483.62                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response LF.PressureMB :
##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Year         1    132  132.16  0.3365 0.5632
## Residuals   92  36128  392.69</code></pre>
<pre class="r"><code>dataomit1 &lt;- dataomit%&gt;% group_by(Year,LF.WindsMPH) %&gt;% filter(n()&gt;1)
pairwise.t.test(dataomit1$LF.WindsMPH, dataomit1$Year, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dataomit1$LF.WindsMPH and dataomit1$Year 
## 
##      1953  1954  1955  1964  1971  2004 
## 1954 0.034 -     -     -     -     -    
## 1955 0.034 1.000 -     -     -     -    
## 1964 0.155 0.275 0.275 -     -     -    
## 1971 1.000 0.034 0.034 0.155 -     -    
## 2004 0.034 1.000 1.000 0.275 0.034 -    
## 2005 0.334 0.098 0.098 0.506 0.334 0.098
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>(1-.95)^24</code></pre>
<pre><code>## [1] 5.960464e-32</code></pre>
<pre class="r"><code>.05/24</code></pre>
<pre><code>## [1] 0.002083333</code></pre>
<p>I performed 1 MANOVA, 2 ANOVAS, and 21 T-test. In total 24 test were run. The probability of at least one type 1 error is 5.960464e-32. The Bonferronis correction is 0.002083333.
A one way MANOVA was used to determine the effect of the Hurricane Year on two dependent variables the LF.WindsMPH and the LF.PressureMB.
There were significant differences found within the two hurricane names for at least one of the dependent variables.
Therefore univariant ANOVAs for each dependent variable were conducted as follow up test to the MANOVA. The univariant ANOVA’S for LF.WindsMPH was the only significant variable as it was less than .05, meaning a post-hoc t.test was performed.
The post hoc analysis showed which Year differed in LF.WindsMPH. The Boneferroni adjustment showed to be 0.002083333. Therefore multiple years were found to differ significantly from each other in terms of LF.WindsMPH.
Some of the assumptions state random samples and independent observations. This is technically not a random sample as some of the data was omitted due to having only one observation in a variable. Another of the assumptions states that there should be no multicollinearity which is assumed and by the t.test seems to show that the dependent variable is not too correlated. Overall the assumptions were not likely to be met.</p>
<p>2.)</p>
<pre class="r"><code>rand_dist&lt;- vector()
for(i in 1:5000){
  new &lt;-data.frame(BaseDamage= sample(hurricNamed$BaseDamage),mf= hurricNamed$mf)
  rand_dist[i] &lt;- mean(new[new$mf== &quot;f&quot;, ]$BaseDamage)-
    mean(new[new$mf == &quot;m&quot;, ]$BaseDamage)
}
hurricNamed %&gt;% group_by(mf)%&gt;% 
  summarize(means=mean(BaseDamage)) %&gt;% 
  summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1         59.1</code></pre>
<pre class="r"><code>{hist(rand_dist, main=&quot;&quot;, ylab=&quot;&quot;); abline(v=59.1, col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>mean(rand_dist&gt;59.1)*2</code></pre>
<pre><code>## [1] 1.0416</code></pre>
<p>Null hypothesis: Mean property damage (BaseDamage) is the same for male vs. female hurricane names.
Alternative hypothesis: Mean property damage is different for male vs female hurricane names.
We fail to reject the null hypothesis because the p-value is greater than .05 which is non-significant.</p>
<p>3.)</p>
<pre class="r"><code>library(ggplot2)
library(sandwich); library(lmtest)
hurricNamed$LF.WindsMPH_c&lt;- hurricNamed$LF.WindsMPH-mean(hurricNamed$LF.WindsMPH)
hurricNamed$LF.PressureMB_c &lt;-hurricNamed$LF.PressureMB-mean(hurricNamed$LF.PressureMB)
fit&lt;-lm(NDAM2014~ LF.WindsMPH_c*LF.PressureMB_c, data=hurricNamed)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = NDAM2014 ~ LF.WindsMPH_c * LF.PressureMB_c, data = hurricNamed)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -32176  -5486  -1228   3159  52116 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   5501.653   1456.294   3.778 0.000284 ***
## LF.WindsMPH_c                 -251.821    113.018  -2.228 0.028363 *  
## LF.PressureMB_c               -649.128    117.675  -5.516 3.29e-07 ***
## LF.WindsMPH_c:LF.PressureMB_c   -7.892      2.267  -3.482 0.000771 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11520 on 90 degrees of freedom
## Multiple R-squared:  0.453,  Adjusted R-squared:  0.4348 
## F-statistic: 24.84 on 3 and 90 DF,  p-value: 8.43e-12</code></pre>
<pre class="r"><code>hurricNamed %&gt;% 
  ggplot(aes(x=NDAM2014, y=LF.WindsMPH_c, color=LF.PressureMB_c)) + 
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;- fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept = 0, color=&#39;red&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.15697, p-value = 0.01726
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 39.813, df = 3, p-value = 1.167e-08</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                                  Estimate Std. Error
## (Intercept)                   5501.653331  1456.2940
## LF.WindsMPH_c                 -251.821202   113.0182
## LF.PressureMB_c               -649.127856   117.6749
## LF.WindsMPH_c:LF.PressureMB_c   -7.892333     2.2668</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                                  Estimate  Std. Error
## (Intercept)                   5501.653331 2670.036533
## LF.WindsMPH_c                 -251.821202  214.902652
## LF.PressureMB_c               -649.127856  270.837943
## LF.WindsMPH_c:LF.PressureMB_c   -7.892333    9.113882</code></pre>
<p>For every damage that had the hurricane appeared in 2014, the maximum sustained windspeed had an average of -251.821mph less than maximum sustained pressure.
Doing the BP test we reject the null hypothesis of equal variance meaning the assumption is violated. The uncorrected standard errors assume the null hypothesis is correct. Coeftest corrects the standard errors to heteroskedasticity standard errors. The estimates are found to be the same but the coeftest standard errors are larger because the null hypothesis is rejected.</p>
<p>R^2 is the proportion of variation in the response variable explained by the model or all predictors at once is 0.453. This means that 45% of variability in NDAM2014 is explained.</p>
<p>4.)</p>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_dat&lt;- sample_frac(hurricNamed, replace=T)
  fit&lt;-lm(NDAM2014~ LF.WindsMPH_c*LF.PressureMB_c, data=boot_dat)
  coef(fit)
})
samp_distn %&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) LF.WindsMPH_c LF.PressureMB_c LF.WindsMPH_c:LF.PressureMB_c
## 1    1783.714      187.8644         233.589                      5.657564</code></pre>
<p>The standard errors of the boostrap compared to the robust SE decreased. Since the standard error of the bootstrap decreased this means the p value would also decrease. As well as the bootstrap standard errors compared to the original SEs are greater meaning the p value will have increased in the bootstrap standard errors because the standard errors are greater than the original SEs.</p>
<p>5.)</p>
<pre class="r"><code>library(tidyverse)

newhurric&lt;-hurricNamed %&gt;% mutate(y=ifelse(mf==&quot;f&quot;, 1,0))
head(newhurric)</code></pre>
<pre><code>## # A tibble: 6 x 16
##   X1    Name   Year LF.WindsMPH LF.PressureMB LF.times BaseDamage NDAM2014
##   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1 Easy… Easy   1950         120           958        1       3.3      1870
## 2 King… King   1950         130           955        1      28        6030
## 3 Able… Able   1952          85           985        1       2.75      170
## 4 Barb… Barb…  1953          85           987        1       1          65
## 5 Flor… Flor…  1953          85           985        1       0.2        18
## 6 Caro… Carol  1954         120           960        2     460.      21375
## # … with 8 more variables: AffectedStates &lt;chr&gt;, firstLF &lt;date&gt;, deaths &lt;dbl&gt;,
## #   mf &lt;chr&gt;, BaseDam2014 &lt;dbl&gt;, LF.WindsMPH_c &lt;dbl&gt;, LF.PressureMB_c &lt;dbl&gt;,
## #   y &lt;dbl&gt;</code></pre>
<pre class="r"><code>fit4&lt;- glm(y~Year+BaseDamage, data=newhurric, family = &quot;binomial&quot;)
coeftest(fit4)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate  Std. Error z value Pr(&gt;|z|)   
## (Intercept)  8.6054e+01  2.8643e+01  3.0043 0.002662 **
## Year        -4.3027e-02  1.4432e-02 -2.9814 0.002869 **
## BaseDamage   2.6788e-05  2.7021e-05  0.9914 0.321509   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit4))</code></pre>
<pre><code>##  (Intercept)         Year   BaseDamage 
## 2.358877e+37 9.578855e-01 1.000027e+00</code></pre>
<pre class="r"><code>newhurric1&lt;- newhurric %&gt;% mutate(prob=predict(fit4, type=&quot;response&quot;),
                          prediction=ifelse(prob&gt;.5,1,0))
newhurric1$mf&lt;-factor(newhurric$mf, levels = c(&quot;f&quot;, &quot;m&quot;))

classify&lt;-newhurric1%&gt;%transmute(prob,prediction,truth=y)

table(prediction=classify$prediction, truth=classify$truth) %&gt;% addmargins()</code></pre>
<pre><code>##           truth
## prediction  0  1 Sum
##        0    6  7  13
##        1   24 57  81
##        Sum 30 64  94</code></pre>
<pre class="r"><code>(6+57)/94</code></pre>
<pre><code>## [1] 0.6702128</code></pre>
<pre class="r"><code>6/13</code></pre>
<pre><code>## [1] 0.4615385</code></pre>
<pre class="r"><code>57/81</code></pre>
<pre><code>## [1] 0.7037037</code></pre>
<pre class="r"><code>6/30</code></pre>
<pre><code>## [1] 0.2</code></pre>
<pre class="r"><code>newhurric1$logit&lt;-predict(fit4,type=&quot;link&quot;)
newhurric1%&gt;%ggplot()+geom_density(aes(logit,color=mf,fill=mf), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=mf))+
  geom_text(x=-5,y=.07,label=&quot;TN = 431&quot;)+
  geom_text(x=-1.75,y=.008,label=&quot;FN = 19&quot;)+
  geom_text(x=1,y=.006,label=&quot;FP = 13&quot;)+
  geom_text(x=5,y=.04,label=&quot;TP = 220&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;- ggplot(classify)+geom_roc(aes(d=truth, m=prob), n.cuts = 0)
ROCplot</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>library(pROC)
calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6916667</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
 
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

newhurric3&lt;- newhurric1 %&gt;% select(-Name) %&gt;% select(-AffectedStates)

set.seed(1234)

fraction&lt;-0.5 
train_n&lt;-floor(fraction*nrow(newhurric3)) 

iter&lt;-500 

diags&lt;-NULL
for(i in 1:iter){
  train_index&lt;-sample(1:nrow(newhurric3),size=train_n)
  train&lt;-newhurric3[train_index,] 
  test&lt;-newhurric3[-train_index,]
  truth&lt;-test$y
  fit&lt;-glm(y~Year+BaseDamage,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens     spec       ppv       auc
## 1 0.6422979 0.8433248 0.234439 0.7037244 0.6560776</code></pre>
<p>The odds of the hurricane being given a female name for each year, and property damage is 2.358877e+37. Controlling for property damage, the odds of being given a female hurricane name increases by a factor of 9.578855e-01 which is not significant. Controlling for year, the odds of being female hurricane name increases by a factor of 1.000027e+00 which is significant. The accuracy is 0.6702128 which is the proportion of the correctly classified hurricane names. The sensitivity 0.4615385 is the true positive rates which is the proportion of female hurricanes names correctly classified. The specificity 0.7037037 is the true negative rate which is the proportion of male hurricane names correctly classified.The PPV precision is 0.2 which is the proportion classified as female hurricane names who actually are.
The auc is 0.6916667 which means the probability that a randomly selected hurricane female name has a higher predicted probability than a randomly selected hurricane male name.After computing the random sub sampling CV the average sensitivity is 0.8415599, the average accuracy is 0.6455319 and the recall is 0.7084499.</p>
<p>6.)</p>
<pre class="r"><code>library(glmnet)
newhurric3&lt;- newhurric1 %&gt;% select(-mf) %&gt;% select(-Name) %&gt;% select(-AffectedStates) %&gt;% select(-X1)
view(newhurric3)
y&lt;- as.matrix(newhurric3$BaseDamage)
x&lt;- newhurric3 %&gt;% mutate_all(scale) %&gt;% as.matrix
cv&lt;- cv.glmnet(x,y)
lasso1&lt;-glmnet(x,y, lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 16 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)      3340.697
## Year                .    
## LF.WindsMPH         .    
## LF.PressureMB       .    
## LF.times            .    
## BaseDamage      10135.675
## NDAM2014            .    
## firstLF             .    
## deaths              .    
## BaseDam2014         .    
## LF.WindsMPH_c       .    
## LF.PressureMB_c     .    
## y                   .    
## prob                .    
## prediction          .    
## logit               .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10 

data5&lt;-newhurric3[sample(nrow(newhurric3)),] 
folds&lt;-cut(seq(1:nrow(newhurric3)),breaks=k,labels=F) 

diags&lt;-NULL
for(i in 1:k){
  train1&lt;-data5[folds!=i,]
  test&lt;-data5[folds==i,]
  
 
  fit&lt;-lm(BaseDamage~.,data=train1)
  
 
  yhat&lt;-predict(fit,newdata=test)
  
 
  diags&lt;-mean((test$BaseDamage-yhat)^2) 
}
mean(diags)</code></pre>
<pre><code>## [1] 2.150103e-18</code></pre>
<p>The variables that are retained are the BaseDamage. The much smaller MSE indicates less overfitting occurring within the model, meaning this would be a good model to make accurate predictions.</p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</div>
